/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackApplicationRouteImport } from './routes/track-application'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RechargePolicyRouteImport } from './routes/recharge-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreatorRewardPolicyRouteImport } from './routes/creator-reward-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoinsRouteImport } from './routes/coins'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JoinWobbRouteImport } from './routes/join.wobb'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogHowToEarnMoneyRouteImport } from './routes/blog.how-to-earn-money-on-poppo-live-india'
import { Route as AdminUpiSetupRouteImport } from './routes/admin.upi-setup'
import { Route as AdminUnmatchedRouteImport } from './routes/admin.unmatched'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminCreatorLeadsRouteImport } from './routes/admin.creator-leads'
import { Route as ApiPublicUpiWebhookRouteImport } from './routes/api/public/upi-webhook'
import { Route as ApiPublicOrderActionRouteImport } from './routes/api/public/order-action'
import { Route as ApiPublicInteraktActionRouteImport } from './routes/api/public/interakt-action'
import { Route as TrackRouteImport } from './routes/track'
import { Route as VerifyRouteImport } from './routes/verify'

const TrackApplicationRoute = TrackApplicationRouteImport.update({
  id: '/track-application',
  path: '/track-application',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargePolicyRoute = RechargePolicyRouteImport.update({
  id: '/recharge-policy',
  path: '/recharge-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRewardPolicyRoute = CreatorRewardPolicyRouteImport.update({
  id: '/creator-reward-policy',
  path: '/creator-reward-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsRoute = CoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JoinWobbRoute = JoinWobbRouteImport.update({
  id: '/wobb',
  path: '/wobb',
  getParentRoute: () => JoinRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BlogHowToEarnMoneyRoute = BlogHowToEarnMoneyRouteImport.update({
  id: '/how-to-earn-money-on-poppo-live-india',
  path: '/how-to-earn-money-on-poppo-live-india',
  getParentRoute: () => BlogRoute,
} as any)
const AdminUpiSetupRoute = AdminUpiSetupRouteImport.update({
  id: '/upi-setup',
  path: '/upi-setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnmatchedRoute = AdminUnmatchedRouteImport.update({
  id: '/unmatched',
  path: '/unmatched',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorLeadsRoute = AdminCreatorLeadsRouteImport.update({
  id: '/creator-leads',
  path: '/creator-leads',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicUpiWebhookRoute = ApiPublicUpiWebhookRouteImport.update({
  id: '/api/public/upi-webhook',
  path: '/api/public/upi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderActionRoute = ApiPublicOrderActionRouteImport.update({
  id: '/api/public/order-action',
  path: '/api/public/order-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInteraktActionRoute = ApiPublicInteraktActionRouteImport.update({
  id: '/api/public/interakt-action',
  path: '/api/public/interakt-action',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/coins': typeof CoinsRoute
  '/contact': typeof ContactRoute
  '/creator-reward-policy': typeof CreatorRewardPolicyRoute
  '/join': typeof JoinRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recharge-policy': typeof RechargePolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRoute
  '/track-application': typeof TrackApplicationRoute
  '/verify': typeof VerifyRoute
  '/admin/creator-leads': typeof AdminCreatorLeadsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/unmatched': typeof AdminUnmatchedRoute
  '/admin/upi-setup': typeof AdminUpiSetupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/how-to-earn-money-on-poppo-live-india': typeof BlogHowToEarnMoneyRoute
  '/blog/how-to-earn-money-on-poppo-live-india': typeof BlogHowToEarnMoneyRoute
  '/join/wobb': typeof JoinWobbRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/interakt-action': typeof ApiPublicInteraktActionRoute
  '/api/public/order-action': typeof ApiPublicOrderActionRoute
  '/api/public/upi-webhook': typeof ApiPublicUpiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/coins': typeof CoinsRoute
  '/contact': typeof ContactRoute
  '/creator-reward-policy': typeof CreatorRewardPolicyRoute
  '/join': typeof JoinRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recharge-policy': typeof RechargePolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRoute
  '/track-application': typeof TrackApplicationRoute
  '/verify': typeof VerifyRoute
  '/admin/creator-leads': typeof AdminCreatorLeadsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/unmatched': typeof AdminUnmatchedRoute
  '/admin/upi-setup': typeof AdminUpiSetupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/how-to-earn-money-on-poppo-live-india': typeof BlogHowToEarnMoneyRoute
  '/blog/how-to-earn-money-on-poppo-live-india': typeof BlogHowToEarnMoneyRoute
  '/join/wobb': typeof JoinWobbRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/interakt-action': typeof ApiPublicInteraktActionRoute
  '/api/public/order-action': typeof ApiPublicOrderActionRoute
  '/api/public/upi-webhook': typeof ApiPublicUpiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/coins': typeof CoinsRoute
  '/contact': typeof ContactRoute
  '/creator-reward-policy': typeof CreatorRewardPolicyRoute
  '/join': typeof JoinRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recharge-policy': typeof RechargePolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRoute
  '/track-application': typeof TrackApplicationRoute
  '/verify': typeof VerifyRoute
  '/admin/creator-leads': typeof AdminCreatorLeadsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/unmatched': typeof AdminUnmatchedRoute
  '/admin/upi-setup': typeof AdminUpiSetupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/how-to-earn-money-on-poppo-live-india': typeof BlogHowToEarnMoneyRoute
  '/blog/how-to-earn-money-on-poppo-live-india': typeof BlogHowToEarnMoneyRoute
  '/join/wobb': typeof JoinWobbRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/interakt-action': typeof ApiPublicInteraktActionRoute
  '/api/public/order-action': typeof ApiPublicOrderActionRoute
  '/api/public/upi-webhook': typeof ApiPublicUpiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/coins'
    | '/contact'
    | '/creator-reward-policy'
    | '/join'
    | '/privacy-policy'
    | '/recharge-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track'
    | '/track-application'
    | '/verify'
    | '/admin/creator-leads'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/policies'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/unmatched'
    | '/admin/upi-setup'
    | '/blog/$slug'
    | '/blog/how-to-earn-money-on-poppo-live-india'
    | '/join/wobb'
    | '/admin/'
    | '/api/public/interakt-action'
    | '/api/public/order-action'
    | '/api/public/upi-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/coins'
    | '/contact'
    | '/creator-reward-policy'
    | '/join'
    | '/privacy-policy'
    | '/recharge-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track'
    | '/track-application'
    | '/verify'
    | '/admin/creator-leads'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/policies'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/unmatched'
    | '/admin/upi-setup'
    | '/blog/$slug'
    | '/blog/how-to-earn-money-on-poppo-live-india'
    | '/join/wobb'
    | '/admin'
    | '/api/public/interakt-action'
    | '/api/public/order-action'
    | '/api/public/upi-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/coins'
    | '/contact'
    | '/creator-reward-policy'
    | '/join'
    | '/privacy-policy'
    | '/recharge-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track'
    | '/track-application'
    | '/verify'
    | '/admin/creator-leads'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/policies'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/unmatched'
    | '/admin/upi-setup'
    | '/blog/$slug'
    | '/blog/how-to-earn-money-on-poppo-live-india'
    | '/join/wobb'
    | '/admin/'
    | '/api/public/interakt-action'
    | '/api/public/order-action'
    | '/api/public/upi-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CoinsRoute: typeof CoinsRoute
  ContactRoute: typeof ContactRoute
  CreatorRewardPolicyRoute: typeof CreatorRewardPolicyRoute
  JoinRoute: typeof JoinRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RechargePolicyRoute: typeof RechargePolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackRoute: typeof TrackRoute
  TrackApplicationRoute: typeof TrackApplicationRoute
  VerifyRoute: typeof VerifyRoute
  ApiPublicInteraktActionRoute: typeof ApiPublicInteraktActionRoute
  ApiPublicOrderActionRoute: typeof ApiPublicOrderActionRoute
  ApiPublicUpiWebhookRoute: typeof ApiPublicUpiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-application': {
      id: '/track-application'
      path: '/track-application'
      fullPath: '/track-application'
      preLoaderRoute: typeof TrackApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge-policy': {
      id: '/recharge-policy'
      path: '/recharge-policy'
      fullPath: '/recharge-policy'
      preLoaderRoute: typeof RechargePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-reward-policy': {
      id: '/creator-reward-policy'
      path: '/creator-reward-policy'
      fullPath: '/creator-reward-policy'
      preLoaderRoute: typeof CreatorRewardPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins': {
      id: '/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/join/wobb': {
      id: '/join/wobb'
      path: '/wobb'
      fullPath: '/join/wobb'
      preLoaderRoute: typeof JoinWobbRouteImport
      parentRoute: typeof JoinRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-to-earn-money-on-poppo-live-india': {
      id: '/blog/how-to-earn-money-on-poppo-live-india'
      path: '/how-to-earn-money-on-poppo-live-india'
      fullPath: '/blog/how-to-earn-money-on-poppo-live-india'
      preLoaderRoute: typeof BlogHowToEarnMoneyRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/upi-setup': {
      id: '/admin/upi-setup'
      path: '/upi-setup'
      fullPath: '/admin/upi-setup'
      preLoaderRoute: typeof AdminUpiSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unmatched': {
      id: '/admin/unmatched'
      path: '/unmatched'
      fullPath: '/admin/unmatched'
      preLoaderRoute: typeof AdminUnmatchedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creator-leads': {
      id: '/admin/creator-leads'
      path: '/creator-leads'
      fullPath: '/admin/creator-leads'
      preLoaderRoute: typeof AdminCreatorLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/upi-webhook': {
      id: '/api/public/upi-webhook'
      path: '/api/public/upi-webhook'
      fullPath: '/api/public/upi-webhook'
      preLoaderRoute: typeof ApiPublicUpiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order-action': {
      id: '/api/public/order-action'
      path: '/api/public/order-action'
      fullPath: '/api/public/order-action'
      preLoaderRoute: typeof ApiPublicOrderActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interakt-action': {
      id: '/api/public/interakt-action'
      path: '/api/public/interakt-action'
      fullPath: '/api/public/interakt-action'
      preLoaderRoute: typeof ApiPublicInteraktActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCreatorLeadsRoute: typeof AdminCreatorLeadsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUnmatchedRoute: typeof AdminUnmatchedRoute
  AdminUpiSetupRoute: typeof AdminUpiSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreatorLeadsRoute: AdminCreatorLeadsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUnmatchedRoute: AdminUnmatchedRoute,
  AdminUpiSetupRoute: AdminUpiSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogHowToEarnMoneyRoute: typeof BlogHowToEarnMoneyRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogHowToEarnMoneyRoute: BlogHowToEarnMoneyRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface JoinRouteChildren {
  JoinWobbRoute: typeof JoinWobbRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinWobbRoute: JoinWobbRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CoinsRoute: CoinsRoute,
  ContactRoute: ContactRoute,
  CreatorRewardPolicyRoute: CreatorRewardPolicyRoute,
  JoinRoute: JoinRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RechargePolicyRoute: RechargePolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackRoute: TrackRoute,
  TrackApplicationRoute: TrackApplicationRoute,
  VerifyRoute: VerifyRoute,
  ApiPublicInteraktActionRoute: ApiPublicInteraktActionRoute,
  ApiPublicOrderActionRoute: ApiPublicOrderActionRoute,
  ApiPublicUpiWebhookRoute: ApiPublicUpiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
