/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TrackApplicationRouteImport } from './routes/track-application'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RechargePolicyRouteImport } from './routes/recharge-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as JoinRouteImport } from './routes/join'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as CreatorRewardPolicyRouteImport } from './routes/creator-reward-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoinsRouteImport } from './routes/coins'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JoinWobbRouteImport } from './routes/join.wobb'
import { Route as AdminUpiSetupRouteImport } from './routes/admin.upi-setup'
import { Route as AdminUnmatchedRouteImport } from './routes/admin.unmatched'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminCreatorLeadsRouteImport } from './routes/admin.creator-leads'
import { Route as AcademyWhatIsPoppoLiveRouteImport } from './routes/academy.what-is-poppo-live'
import { Route as AcademyVoneAppIndiaRouteImport } from './routes/academy.vone-app-india'
import { Route as AcademyPoppoWithdrawalGuideRouteImport } from './routes/academy.poppo-withdrawal-guide'
import { Route as AcademyPoppoLiveEarningIndiaRouteImport } from './routes/academy.poppo-live-earning-india'
import { Route as AcademyPoppoDailyTasksRouteImport } from './routes/academy.poppo-daily-tasks'
import { Route as AcademyPkBattleGuideRouteImport } from './routes/academy.pk-battle-guide'
import { Route as AcademyHowToBecomePoppoHostRouteImport } from './routes/academy.how-to-become-poppo-host'
import { Route as AcademyCoinsPointsGiftsExplainedRouteImport } from './routes/academy.coins-points-gifts-explained'
import { Route as ApiPublicUpiWebhookRouteImport } from './routes/api/public/upi-webhook'
import { Route as ApiPublicOrderActionRouteImport } from './routes/api/public/order-action'
import { Route as ApiPublicInteraktActionRouteImport } from './routes/api/public/interakt-action'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackApplicationRoute = TrackApplicationRouteImport.update({
  id: '/track-application',
  path: '/track-application',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargePolicyRoute = RechargePolicyRouteImport.update({
  id: '/recharge-policy',
  path: '/recharge-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRewardPolicyRoute = CreatorRewardPolicyRouteImport.update({
  id: '/creator-reward-policy',
  path: '/creator-reward-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsRoute = CoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JoinWobbRoute = JoinWobbRouteImport.update({
  id: '/wobb',
  path: '/wobb',
  getParentRoute: () => JoinRoute,
} as any)
const AdminUpiSetupRoute = AdminUpiSetupRouteImport.update({
  id: '/upi-setup',
  path: '/upi-setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnmatchedRoute = AdminUnmatchedRouteImport.update({
  id: '/unmatched',
  path: '/unmatched',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorLeadsRoute = AdminCreatorLeadsRouteImport.update({
  id: '/creator-leads',
  path: '/creator-leads',
  getParentRoute: () => AdminRoute,
} as any)
const AcademyWhatIsPoppoLiveRoute = AcademyWhatIsPoppoLiveRouteImport.update({
  id: '/what-is-poppo-live',
  path: '/what-is-poppo-live',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyVoneAppIndiaRoute = AcademyVoneAppIndiaRouteImport.update({
  id: '/vone-app-india',
  path: '/vone-app-india',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyPoppoWithdrawalGuideRoute =
  AcademyPoppoWithdrawalGuideRouteImport.update({
    id: '/poppo-withdrawal-guide',
    path: '/poppo-withdrawal-guide',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyPoppoLiveEarningIndiaRoute =
  AcademyPoppoLiveEarningIndiaRouteImport.update({
    id: '/poppo-live-earning-india',
    path: '/poppo-live-earning-india',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyPoppoDailyTasksRoute = AcademyPoppoDailyTasksRouteImport.update({
  id: '/poppo-daily-tasks',
  path: '/poppo-daily-tasks',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyPkBattleGuideRoute = AcademyPkBattleGuideRouteImport.update({
  id: '/pk-battle-guide',
  path: '/pk-battle-guide',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyHowToBecomePoppoHostRoute =
  AcademyHowToBecomePoppoHostRouteImport.update({
    id: '/how-to-become-poppo-host',
    path: '/how-to-become-poppo-host',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyCoinsPointsGiftsExplainedRoute =
  AcademyCoinsPointsGiftsExplainedRouteImport.update({
    id: '/coins-points-gifts-explained',
    path: '/coins-points-gifts-explained',
    getParentRoute: () => AcademyRoute,
  } as any)
const ApiPublicUpiWebhookRoute = ApiPublicUpiWebhookRouteImport.update({
  id: '/api/public/upi-webhook',
  path: '/api/public/upi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderActionRoute = ApiPublicOrderActionRouteImport.update({
  id: '/api/public/order-action',
  path: '/api/public/order-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInteraktActionRoute = ApiPublicInteraktActionRouteImport.update({
  id: '/api/public/interakt-action',
  path: '/api/public/interakt-action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/coins': typeof CoinsRoute
  '/contact': typeof ContactRoute
  '/creator-reward-policy': typeof CreatorRewardPolicyRoute
  '/earnings': typeof EarningsRoute
  '/join': typeof JoinRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recharge-policy': typeof RechargePolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRoute
  '/track-application': typeof TrackApplicationRoute
  '/verify': typeof VerifyRoute
  '/academy/coins-points-gifts-explained': typeof AcademyCoinsPointsGiftsExplainedRoute
  '/academy/how-to-become-poppo-host': typeof AcademyHowToBecomePoppoHostRoute
  '/academy/pk-battle-guide': typeof AcademyPkBattleGuideRoute
  '/academy/poppo-daily-tasks': typeof AcademyPoppoDailyTasksRoute
  '/academy/poppo-live-earning-india': typeof AcademyPoppoLiveEarningIndiaRoute
  '/academy/poppo-withdrawal-guide': typeof AcademyPoppoWithdrawalGuideRoute
  '/academy/vone-app-india': typeof AcademyVoneAppIndiaRoute
  '/academy/what-is-poppo-live': typeof AcademyWhatIsPoppoLiveRoute
  '/admin/creator-leads': typeof AdminCreatorLeadsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/unmatched': typeof AdminUnmatchedRoute
  '/admin/upi-setup': typeof AdminUpiSetupRoute
  '/join/wobb': typeof JoinWobbRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/interakt-action': typeof ApiPublicInteraktActionRoute
  '/api/public/order-action': typeof ApiPublicOrderActionRoute
  '/api/public/upi-webhook': typeof ApiPublicUpiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/coins': typeof CoinsRoute
  '/contact': typeof ContactRoute
  '/creator-reward-policy': typeof CreatorRewardPolicyRoute
  '/earnings': typeof EarningsRoute
  '/join': typeof JoinRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recharge-policy': typeof RechargePolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRoute
  '/track-application': typeof TrackApplicationRoute
  '/verify': typeof VerifyRoute
  '/academy/coins-points-gifts-explained': typeof AcademyCoinsPointsGiftsExplainedRoute
  '/academy/how-to-become-poppo-host': typeof AcademyHowToBecomePoppoHostRoute
  '/academy/pk-battle-guide': typeof AcademyPkBattleGuideRoute
  '/academy/poppo-daily-tasks': typeof AcademyPoppoDailyTasksRoute
  '/academy/poppo-live-earning-india': typeof AcademyPoppoLiveEarningIndiaRoute
  '/academy/poppo-withdrawal-guide': typeof AcademyPoppoWithdrawalGuideRoute
  '/academy/vone-app-india': typeof AcademyVoneAppIndiaRoute
  '/academy/what-is-poppo-live': typeof AcademyWhatIsPoppoLiveRoute
  '/admin/creator-leads': typeof AdminCreatorLeadsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/unmatched': typeof AdminUnmatchedRoute
  '/admin/upi-setup': typeof AdminUpiSetupRoute
  '/join/wobb': typeof JoinWobbRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/interakt-action': typeof ApiPublicInteraktActionRoute
  '/api/public/order-action': typeof ApiPublicOrderActionRoute
  '/api/public/upi-webhook': typeof ApiPublicUpiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/coins': typeof CoinsRoute
  '/contact': typeof ContactRoute
  '/creator-reward-policy': typeof CreatorRewardPolicyRoute
  '/earnings': typeof EarningsRoute
  '/join': typeof JoinRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/recharge-policy': typeof RechargePolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRoute
  '/track-application': typeof TrackApplicationRoute
  '/verify': typeof VerifyRoute
  '/academy/coins-points-gifts-explained': typeof AcademyCoinsPointsGiftsExplainedRoute
  '/academy/how-to-become-poppo-host': typeof AcademyHowToBecomePoppoHostRoute
  '/academy/pk-battle-guide': typeof AcademyPkBattleGuideRoute
  '/academy/poppo-daily-tasks': typeof AcademyPoppoDailyTasksRoute
  '/academy/poppo-live-earning-india': typeof AcademyPoppoLiveEarningIndiaRoute
  '/academy/poppo-withdrawal-guide': typeof AcademyPoppoWithdrawalGuideRoute
  '/academy/vone-app-india': typeof AcademyVoneAppIndiaRoute
  '/academy/what-is-poppo-live': typeof AcademyWhatIsPoppoLiveRoute
  '/admin/creator-leads': typeof AdminCreatorLeadsRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/unmatched': typeof AdminUnmatchedRoute
  '/admin/upi-setup': typeof AdminUpiSetupRoute
  '/join/wobb': typeof JoinWobbRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/interakt-action': typeof ApiPublicInteraktActionRoute
  '/api/public/order-action': typeof ApiPublicOrderActionRoute
  '/api/public/upi-webhook': typeof ApiPublicUpiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/admin'
    | '/coins'
    | '/contact'
    | '/creator-reward-policy'
    | '/earnings'
    | '/join'
    | '/privacy-policy'
    | '/recharge-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track'
    | '/track-application'
    | '/verify'
    | '/academy/coins-points-gifts-explained'
    | '/academy/how-to-become-poppo-host'
    | '/academy/pk-battle-guide'
    | '/academy/poppo-daily-tasks'
    | '/academy/poppo-live-earning-india'
    | '/academy/poppo-withdrawal-guide'
    | '/academy/vone-app-india'
    | '/academy/what-is-poppo-live'
    | '/admin/creator-leads'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/unmatched'
    | '/admin/upi-setup'
    | '/join/wobb'
    | '/admin/'
    | '/api/public/interakt-action'
    | '/api/public/order-action'
    | '/api/public/upi-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/coins'
    | '/contact'
    | '/creator-reward-policy'
    | '/earnings'
    | '/join'
    | '/privacy-policy'
    | '/recharge-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track'
    | '/track-application'
    | '/verify'
    | '/academy/coins-points-gifts-explained'
    | '/academy/how-to-become-poppo-host'
    | '/academy/pk-battle-guide'
    | '/academy/poppo-daily-tasks'
    | '/academy/poppo-live-earning-india'
    | '/academy/poppo-withdrawal-guide'
    | '/academy/vone-app-india'
    | '/academy/what-is-poppo-live'
    | '/admin/creator-leads'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/unmatched'
    | '/admin/upi-setup'
    | '/join/wobb'
    | '/admin'
    | '/api/public/interakt-action'
    | '/api/public/order-action'
    | '/api/public/upi-webhook'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/admin'
    | '/coins'
    | '/contact'
    | '/creator-reward-policy'
    | '/earnings'
    | '/join'
    | '/privacy-policy'
    | '/recharge-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track'
    | '/track-application'
    | '/verify'
    | '/academy/coins-points-gifts-explained'
    | '/academy/how-to-become-poppo-host'
    | '/academy/pk-battle-guide'
    | '/academy/poppo-daily-tasks'
    | '/academy/poppo-live-earning-india'
    | '/academy/poppo-withdrawal-guide'
    | '/academy/vone-app-india'
    | '/academy/what-is-poppo-live'
    | '/admin/creator-leads'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/unmatched'
    | '/admin/upi-setup'
    | '/join/wobb'
    | '/admin/'
    | '/api/public/interakt-action'
    | '/api/public/order-action'
    | '/api/public/upi-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CoinsRoute: typeof CoinsRoute
  ContactRoute: typeof ContactRoute
  CreatorRewardPolicyRoute: typeof CreatorRewardPolicyRoute
  EarningsRoute: typeof EarningsRoute
  JoinRoute: typeof JoinRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RechargePolicyRoute: typeof RechargePolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackRoute: typeof TrackRoute
  TrackApplicationRoute: typeof TrackApplicationRoute
  VerifyRoute: typeof VerifyRoute
  ApiPublicInteraktActionRoute: typeof ApiPublicInteraktActionRoute
  ApiPublicOrderActionRoute: typeof ApiPublicOrderActionRoute
  ApiPublicUpiWebhookRoute: typeof ApiPublicUpiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-application': {
      id: '/track-application'
      path: '/track-application'
      fullPath: '/track-application'
      preLoaderRoute: typeof TrackApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge-policy': {
      id: '/recharge-policy'
      path: '/recharge-policy'
      fullPath: '/recharge-policy'
      preLoaderRoute: typeof RechargePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-reward-policy': {
      id: '/creator-reward-policy'
      path: '/creator-reward-policy'
      fullPath: '/creator-reward-policy'
      preLoaderRoute: typeof CreatorRewardPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins': {
      id: '/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/join/wobb': {
      id: '/join/wobb'
      path: '/wobb'
      fullPath: '/join/wobb'
      preLoaderRoute: typeof JoinWobbRouteImport
      parentRoute: typeof JoinRoute
    }
    '/admin/upi-setup': {
      id: '/admin/upi-setup'
      path: '/upi-setup'
      fullPath: '/admin/upi-setup'
      preLoaderRoute: typeof AdminUpiSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unmatched': {
      id: '/admin/unmatched'
      path: '/unmatched'
      fullPath: '/admin/unmatched'
      preLoaderRoute: typeof AdminUnmatchedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creator-leads': {
      id: '/admin/creator-leads'
      path: '/creator-leads'
      fullPath: '/admin/creator-leads'
      preLoaderRoute: typeof AdminCreatorLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/academy/what-is-poppo-live': {
      id: '/academy/what-is-poppo-live'
      path: '/what-is-poppo-live'
      fullPath: '/academy/what-is-poppo-live'
      preLoaderRoute: typeof AcademyWhatIsPoppoLiveRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/vone-app-india': {
      id: '/academy/vone-app-india'
      path: '/vone-app-india'
      fullPath: '/academy/vone-app-india'
      preLoaderRoute: typeof AcademyVoneAppIndiaRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/poppo-withdrawal-guide': {
      id: '/academy/poppo-withdrawal-guide'
      path: '/poppo-withdrawal-guide'
      fullPath: '/academy/poppo-withdrawal-guide'
      preLoaderRoute: typeof AcademyPoppoWithdrawalGuideRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/poppo-live-earning-india': {
      id: '/academy/poppo-live-earning-india'
      path: '/poppo-live-earning-india'
      fullPath: '/academy/poppo-live-earning-india'
      preLoaderRoute: typeof AcademyPoppoLiveEarningIndiaRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/poppo-daily-tasks': {
      id: '/academy/poppo-daily-tasks'
      path: '/poppo-daily-tasks'
      fullPath: '/academy/poppo-daily-tasks'
      preLoaderRoute: typeof AcademyPoppoDailyTasksRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/pk-battle-guide': {
      id: '/academy/pk-battle-guide'
      path: '/pk-battle-guide'
      fullPath: '/academy/pk-battle-guide'
      preLoaderRoute: typeof AcademyPkBattleGuideRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/how-to-become-poppo-host': {
      id: '/academy/how-to-become-poppo-host'
      path: '/how-to-become-poppo-host'
      fullPath: '/academy/how-to-become-poppo-host'
      preLoaderRoute: typeof AcademyHowToBecomePoppoHostRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/coins-points-gifts-explained': {
      id: '/academy/coins-points-gifts-explained'
      path: '/coins-points-gifts-explained'
      fullPath: '/academy/coins-points-gifts-explained'
      preLoaderRoute: typeof AcademyCoinsPointsGiftsExplainedRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/api/public/upi-webhook': {
      id: '/api/public/upi-webhook'
      path: '/api/public/upi-webhook'
      fullPath: '/api/public/upi-webhook'
      preLoaderRoute: typeof ApiPublicUpiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order-action': {
      id: '/api/public/order-action'
      path: '/api/public/order-action'
      fullPath: '/api/public/order-action'
      preLoaderRoute: typeof ApiPublicOrderActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/interakt-action': {
      id: '/api/public/interakt-action'
      path: '/api/public/interakt-action'
      fullPath: '/api/public/interakt-action'
      preLoaderRoute: typeof ApiPublicInteraktActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcademyRouteChildren {
  AcademyCoinsPointsGiftsExplainedRoute: typeof AcademyCoinsPointsGiftsExplainedRoute
  AcademyHowToBecomePoppoHostRoute: typeof AcademyHowToBecomePoppoHostRoute
  AcademyPkBattleGuideRoute: typeof AcademyPkBattleGuideRoute
  AcademyPoppoDailyTasksRoute: typeof AcademyPoppoDailyTasksRoute
  AcademyPoppoLiveEarningIndiaRoute: typeof AcademyPoppoLiveEarningIndiaRoute
  AcademyPoppoWithdrawalGuideRoute: typeof AcademyPoppoWithdrawalGuideRoute
  AcademyVoneAppIndiaRoute: typeof AcademyVoneAppIndiaRoute
  AcademyWhatIsPoppoLiveRoute: typeof AcademyWhatIsPoppoLiveRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyCoinsPointsGiftsExplainedRoute: AcademyCoinsPointsGiftsExplainedRoute,
  AcademyHowToBecomePoppoHostRoute: AcademyHowToBecomePoppoHostRoute,
  AcademyPkBattleGuideRoute: AcademyPkBattleGuideRoute,
  AcademyPoppoDailyTasksRoute: AcademyPoppoDailyTasksRoute,
  AcademyPoppoLiveEarningIndiaRoute: AcademyPoppoLiveEarningIndiaRoute,
  AcademyPoppoWithdrawalGuideRoute: AcademyPoppoWithdrawalGuideRoute,
  AcademyVoneAppIndiaRoute: AcademyVoneAppIndiaRoute,
  AcademyWhatIsPoppoLiveRoute: AcademyWhatIsPoppoLiveRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface AdminRouteChildren {
  AdminCreatorLeadsRoute: typeof AdminCreatorLeadsRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUnmatchedRoute: typeof AdminUnmatchedRoute
  AdminUpiSetupRoute: typeof AdminUpiSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCreatorLeadsRoute: AdminCreatorLeadsRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUnmatchedRoute: AdminUnmatchedRoute,
  AdminUpiSetupRoute: AdminUpiSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JoinRouteChildren {
  JoinWobbRoute: typeof JoinWobbRoute
}

const JoinRouteChildren: JoinRouteChildren = {
  JoinWobbRoute: JoinWobbRoute,
}

const JoinRouteWithChildren = JoinRoute._addFileChildren(JoinRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CoinsRoute: CoinsRoute,
  ContactRoute: ContactRoute,
  CreatorRewardPolicyRoute: CreatorRewardPolicyRoute,
  EarningsRoute: EarningsRoute,
  JoinRoute: JoinRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RechargePolicyRoute: RechargePolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackRoute: TrackRoute,
  TrackApplicationRoute: TrackApplicationRoute,
  VerifyRoute: VerifyRoute,
  ApiPublicInteraktActionRoute: ApiPublicInteraktActionRoute,
  ApiPublicOrderActionRoute: ApiPublicOrderActionRoute,
  ApiPublicUpiWebhookRoute: ApiPublicUpiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
